name = "gemini-research-bridge"
main = "src/index.ts"
compatibility_date = "2026-08-30"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "gemini-research-bridge"
database_id = "b253bd41-2273-47d7-acbf-d27228ded3d0"
